### ISSUE TITLE
non-zero covariance mixture models

### ISSUE THREAD

**Issue by changhoonhahn** [VMBoehm/MnuLFI#2]
In the current pyDELFI implementation, mixture models for NDE can have zero covariance, which results in weird posteriors. @VMBoehm @eiffl

**Comment by VMBoehm** [comment]
added option to add offset to diagonal of the mixture covariances (use pydelfi on branch 'stable', https://github.com/VMBoehm/pydelfi/tree/stable)
Usage: pass an offset parameter (default 1e-6) to MixtureDensityNetwork. Example in https://github.com/VMBoehm/pydelfi/blob/stable/examples/cosmic_shear_prerun_sims-changing_params.ipynb
